schema_version = "1.0.0"

blender_version_min = "4.4.0"
id = "Bbrush"
license = ["SPDX:GPL-3.0-or-later", ]
maintainer = "AIGODLIKE Community(小萌新)"
name = "Bbrush"
tagline = "Entering the sculpt mode will be displayed in the top bar"
type = "add-on"
version = "1.3.0"
tags = ["Sculpt", ]

[permissions]
files = "Keymap File Load"