schema_version = "1.0.0"

blender_version_min = "4.4.0"
id = "Bbrush"
license = ["SPDX:GPL-3.0-or-later", ]
maintainer = "AIGODLIKE Community(小萌新)"
name = "Bbrush"
tagline = "Sculpting using only a pen and keyboard"
type = "add-on"
version = "1.3.3"
tags = ["Sculpt", ]

[permissions]
files = "Keymap File Load"