schema_version = "1.0.3"

blender_version_min = "4.4.0"
id = "Bbrush"
license = ["UNKNOWN", ]
maintainer = "AIGODLIKE Community：小萌新"
name = "Bbrush"
tagline = "Entering the sculpt mode will be displayed in the top bar"
type = "add-on"
version = "1.3.0"
tags = ["幻之境", "AIGODLIKE Community"]
