DEBUG_MODE_TOGGLE = False
DEBUG_KEYMAP = False
DEBUG_UPDATE_BRUSH_SHELF = True
DEBUG_VIEW_PREF = False

DEBUG_LEFT_MOUSE = False
DEBUG_CLICK = False
DEBUG_DRAG = False
DEBUG_SMOOTH = False

DEBUG_DEPTH_MAP = False
