data = {
    "Select Box": "框选",
    "Select Lasoo": "套索选择",
    "Entering the sculpt mode will be displayed in the top bar": "进入雕刻模式将会在顶栏显示",
    "theKeyActionIsAClick": "按键操作是单击",
    "writePropertyFileError": "写入属性文件错误",
    "DisplayedAllTheTime": "一直显示",
    "SculptModeOnly": "仅雕刻模式",
    "BbrushModeOnly": "仅Bbrush模式",
    "NotShown": "不显示",
    "Keep the silhouette displayed all the time, even when not in sculpting mode": "一直保持显示剪影图,即使不在雕刻模式",
    "Display silhouette images only in sculpting mode": "仅在雕刻模式显示剪影图",
    "Only in Bbrush mode, the silhouette is displayed": "仅在Bbrush模式时,显示剪影图",
    "Never display silhouette images at any time": "任何时候都不显示剪影图",
    "Silhouette Display Mode": "剪影图显示模式",
    "Silhouette image scaling": "剪影图缩放",
    "Silhouette image offset X": "剪影图偏移X",
    "Silhouette image offset Y": "剪影图偏移Y",
    "Shortcut key offset X": "快捷键偏移X",
    "Shortcut key offset Y": "快捷键偏移Y",
    "Always use Bbrush sculpting mode": "始终使用Bbrush雕刻模式",
    "If entering sculpting mode, Bbrush mode will automatically activate; if exiting sculpting mode, Bbrush mode will deactivate": "如果进入雕刻模式则自动开启Bbrush模式,退出雕刻模式则退出Bbrush模式",
    "Depth ray check size": "深度射线检查大小",
    "Display shortcut keys": "显示快捷键",
    "Shortcut key offset": "快捷键偏移",
    "Shortcut key display size": "快捷键显示大小",
    "Silhouette": "剪影图",
    "Shortcut": "快捷键",
    "Setting log file path error": "设置Log文件路径错误",
    "Check if the mouse is placed over the model, mouse cursor range size": "检查鼠标是否放在模型上,鼠标范围大小",
    "Control handle for moving the sculpting origin": "用于移动雕刻原点的操作控制柄",
    "Polygon mask": "多边形绘制遮罩",
    "Draw polygonal mask": "绘制多边形遮罩",
    "Square mask": "方形绘制遮罩",
    "Draw square mask": "绘制方形遮罩",
    "Circular mask": "圆形绘制遮罩",
    "Draw circular mask": "绘制圆形遮罩",
    "Ellipse mask": "椭圆遮罩",
    "Draw elliptical mask": "绘制椭圆遮罩",
    "View operations": "视图操作",
    "Pan view": "平移视图",
    "Rotate view": "旋转视图",
    "Zoom view": "缩放视图",
    "Tilt view": "倾斜视图",
    "alt+right or alt+middle": "ALT+右键 or ALT+中键",
    "alt+left Drag in blank area": "在空白处ALT+左键拖拽",
    "shift+middle": "shift+中键",
    "left Drag in blank area": "在空白处左键拖拽",
    "ctrl+middle or ctrl+right": "ctrl+中键 或 ctrl+右键",
    "shift+left Drag in blank area": "在空白处shift+左键拖拽",
    "left Paint on the model": "左键在模型上绘制",
    "alt+left Paint on the model": "alt+左键在模型上绘制",
    "shift+left Paint on the model": "shift+左键在模型上绘制",
    "alt+left Click on other models": "alt+左键在模型上单击",
    "ctrl+left Paint on the model": "ctrl+左键在模型上绘制",
    "ctrl+alt+left Paint on the model": "ctrl+alt+左键在模型上绘制",
    "ctrl+left Drag in blank area": "在空白处ctrl+左键拖拽",
    "ctrl+left Drag from a blank area to the model": "在空白处ctrl+左键拖拽到模型上",
    "ctrl+alt+left Drag from a blank area to the model": "在空白处ctrl+alt+左键拖拽到模型上",
    "ctrl+left Click on the model": "ctrl+左键单击模型",
    "ctrl+alt+left Click on the model": "ctrl+alt+左键在模型上单击",
    "ctrl+alt+left Drag in blank area": "在空白处ctrl+alt+左键拖拽",
    "ctrl+Numpad+ Click": "ctrl+数字+ 左键单击",
    "ctrl+Numpad- Click": "ctrl+数字- 左键单击",
    "ctrl+Up arrow or ctrl+Numpad* Click": "ctrl+方向上 或 数字* 左键单击",
    "ctrl+Down arrow or ctrl+Numpad/ Click": "ctrl+方向下 或 数字/ 左键单击",
    "ctrl+shift+left Paint on the model": "ctrl+shift+左键在模型上绘制",
    "ctrl+shift+alt+left Paint on the model": "ctrl+shift+alt+左键在模型上绘制",
    "ctrl+shift+left Click in blank area": "在空白处ctrl+shift+左键单击",
    "ctrl+shift+left or ctrl+shift+alt+left Drag in blank area": "在空白处ctrl+shift 或 ctrl+shift+alt+左键拖拽",

    "mouse_right": "右键",
    "middle": "中键",
    "left": "左键",
    "click": "单击",
    "Numpad": "小键盘",
    "Reverse sculpt": "反向雕刻",
    "Smooth": "平滑",
    "Switch object": "切换雕刻物体",
    "Draw mask": "绘制遮罩",
    "Erase mask": "擦除遮罩",
    "Invert mask": "反转遮罩",
    "Marquee mask": "框选遮罩",
    "erase mask": "框选擦除遮罩",
    "Fade mask": "淡化遮罩",
    "Clear mask": "清除遮罩",
    "Sharpen mask": "锐化遮罩",
    "Fill mask": "填充遮罩",
    "Grow mask": "生长遮罩",
    "Shrink mask": "收缩遮罩",
    "Increase contrast": "提高遮罩对比度",
    "Decrease contrast": "降低遮罩对比度",
    "Hide": "隐藏",
    "Hide outside": "隐藏绘制框外",
    "Hide inside": "隐藏绘制框内",
    "Unhide": "取消隐藏",
    "Invert visibility": "反转隐藏",
    "Up arrow": "上箭头",
    "Down arrow": "下箭头",
    "Brush mode switch": "笔刷模式切换",
    "Switch brush content, with a list of options for each key, including [sculpt, mask, hide]": "切换笔刷内容,每个键的列表，有[雕刻,遮罩,隐藏]三个功能",
    "Depth map zoom value": "深度图缩放值",
    "Bbrush sculpting": "Bbrush雕刻",
    "Sculpting in the style of Zbrush": "使用Zbrush的方式雕刻",
    "Only the front faces": "仅前面的面",
    "The key operation is a single click": "按键操作是单击",
    "Error in acquiring shape projection": "获取形状投射错误",
    "Bbrush mask": "Bbrush遮罩",
    "Mask brush": "遮罩笔刷",
    "Display top text": "显示顶部文本",
    "Depth ray check size(px)": "深度射线检查大小(px)",
    "Replace top bar": "替换顶部栏",
    "LIFT": "左",
    "CENTER": "中",
    "Top bar": "顶部栏",
}
